
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      DefaultZone: http://discovery-server:8761/eureka

server:
  port: 8060
spring:
  application:
    name: medical-record
  config:
    import: optional:configserver:http://localhost:8888


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nexthealth_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    users-url: http://gateway-app:8080/api/v1/users-structures
    appointments-url: http://appointments:8070/api/v1
