# Generated by Django 4.2 on 2024-06-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_consultation_ordonnance_delete_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='description',
            field=models.TextField(),
        ),
    ]
